# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fifthPageView.ui'
#
# Created: Fri May 20 11:22:36 2016
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fifthPage(object):
    def setupUi(self, fifthPage):
        fifthPage.setObjectName("fifthPage")
        fifthPage.resize(498, 965)
        self.gridLayout = QtWidgets.QGridLayout(fifthPage)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(fifthPage)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(fifthPage)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 9, 1, 1, 1)
        self.label = QtWidgets.QLabel(fifthPage)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(fifthPage)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(fifthPage)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(fifthPage)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(fifthPage)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(fifthPage)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(fifthPage)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(fifthPage)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(fifthPage)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(fifthPage)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 8, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(fifthPage)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 8, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(fifthPage)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(fifthPage)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(fifthPage)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 9, 0, 1, 1)

        self.retranslateUi(fifthPage)
        QtCore.QMetaObject.connectSlotsByName(fifthPage)

    def retranslateUi(self, fifthPage):
        _translate = QtCore.QCoreApplication.translate
        fifthPage.setWindowTitle(_translate("fifthPage", "WizardPage"))
        self.label_7.setText(_translate("fifthPage", "TextLabel"))
        self.label_15.setText(_translate("fifthPage", "TextLabel"))
        self.label.setText(_translate("fifthPage", "Imie:"))
        self.label_2.setText(_translate("fifthPage", "Nazwisko:"))
        self.label_5.setText(_translate("fifthPage", "TextLabel"))
        self.label_6.setText(_translate("fifthPage", "TextLabel"))
        self.label_4.setText(_translate("fifthPage", "Telefon:"))
        self.label_3.setText(_translate("fifthPage", "Kod:"))
        self.label_8.setText(_translate("fifthPage", "TextLabel"))
        self.label_16.setText(_translate("fifthPage", "Adres"))
        self.label_10.setText(_translate("fifthPage", "Miasto:"))
        self.label_12.setText(_translate("fifthPage", "Ulica:"))
        self.label_13.setText(_translate("fifthPage", "TextLabel"))
        self.label_9.setText(_translate("fifthPage", "Twoje dane:"))
        self.label_11.setText(_translate("fifthPage", "TextLabel"))
        self.label_14.setText(_translate("fifthPage", "Nr budynku/mieszkania:"))

